version: '3.8'

services:
    app:
        image: node18 #Construir imagen del Dockerfile, puede quitar esta linea, colocando la siguiente: build: ./app
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./app:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: portfolio

    mysql:
          image: mysql:5.7
          ports:
            - 3307:3306
          volumes:
            - app:/var/lib/mysql
          environment:
              MYSQL_ROOT_PASSWORD: secret
              MYSQL_DATABASE: portfolio
volumes:
    app: