version: '3.8'

services:
    app:
        image: node:18.15.0-alpine3.16
        build: .
        ports:
          - 3000:3000

        volumes:
          - ./app:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: portfolio

    mysql:
          image: mysql:5.7
          ports:
            - 3307:3306
          volumes:
            - app:/var/lib/mysql
          environment:
              MYSQL_ROOT_PASSWORD: secret
              MYSQL_DATABASE: portfolio
volumes:
    app: